# Application information
server:
  port: 8080
  contextPath: /paraconsistente

##Test
#spring:
#  profiles: local, default
#datasource:
#  sampleapp:
#    url: jdbc:h2:~/test
#    username: SA
#    password:
#    driverClassName: org.h2.Driver
#    defaultSchema:
#    maxPoolSize: 10
#    hibernate:
#      hbm2ddl.method: create-drop
#      show_sql: true
#      format_sql: true
#      dialect: org.hibernate.dialect.H2Dialect
      
#Prod - SOMENTE NA INTERNET
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:mysql://mycfpsapf.mysql.dbaas.com.br:3306/mycfpsapf
    username: mycfpsapf
    password: apf@109
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    tomcat:
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

# Logging properties
logging.file: measurementService.log
server.tomcat.basedir: target/tomcat
server.tomcat.access_log_enabled: true
server.tomcat.access_log_pattern: '%h %t "%r" %s %b'

# Version & debug information
info.app.name: Paraconsistente
info.app.description: Testar o software de paraconsistente do Prof. Luiz
info.app.version: 1.0
